root = "."
testdata_dir = "testdata"
bin_dir = "bin"

[build]
  args_bin = []
  bin = "./tmp/main"
  cmd = "CGO_ENABLED=1 go build -o ./tmp/main ./cmd/boilerplate"
  delay = 1000
  exclude_dir = ["assets", "bin", "vendor", "testdata"]
  exclude_file = []
  exclude_regex = ["_test.go", "/web", "/node_modules"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  include_file = []
  kill_delay = "0s"
  log = "build-errors.log"
  poll = false
  poll_interval = 0
  rerun = false
  rerun_delay = 500
  send_interrupt = false
  stop_on_root = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  main_only = false
  time = false

[misc]
  clean_on_exit = false

[screen]
  clear_on_rebuild = false
  keep_scroll = true
